"""grand_unification_3_pile

Revision ID: 12e4dc0b67b8
Revises: c8d41f0a2b77
Create Date: 2026-05-09 13:50:37.299106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12e4dc0b67b8'
down_revision: Union[str, Sequence[str], None] = 'c8d41f0a2b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'ELECTRONICS', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'PERSONAL_CARE', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'BANK_FEES_INTEREST', 'DEBT_CHARGES', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', name='expensecategory', create_type=False), nullable=False),
    sa.Column('budget_year', sa.Integer(), nullable=False),
    sa.Column('budget_month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.Enum('ROLLOVER', 'SWEEP', 'CAP_TRIM', name='budgetledgertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'category', 'budget_year', 'budget_month', 'entry_type', name='uq_budget_ledger_unique_entry')
    )
    op.create_index(op.f('ix_budget_ledger_id'), 'budget_ledger', ['id'], unique=False)
    op.create_index('ix_budget_ledger_lookup', 'budget_ledger', ['owner_id', 'category', 'budget_year', 'budget_month'], unique=False)
    op.create_table('financial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('event_type', postgresql.ENUM('EXPENSE', 'INCOME', 'TRANSFER', 'REFUND', 'ADJUSTMENT', 'DEBT_SETTLEMENT', 'NEUTRAL_FLOW', name='transactiontype', create_type=False), nullable=False),
    sa.Column('linked_event_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_event_id'], ['financial_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_events_event_type'), 'financial_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_financial_events_id'), 'financial_events', ['id'], unique=False)
    op.create_index(op.f('ix_financial_events_owner_id'), 'financial_events', ['owner_id'], unique=False)
    op.create_table('user_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'ELECTRONICS', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'PERSONAL_CARE', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'BANK_FEES_INTEREST', 'DEBT_CHARGES', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', name='expensecategory', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monthly_limit', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'category', 'name', name='uq_user_subcats_owner_cat_name')
    )
    op.create_index(op.f('ix_user_subcategories_id'), 'user_subcategories', ['id'], unique=False)
    op.create_index('ix_user_subcategories_owner_category', 'user_subcategories', ['owner_id', 'category'], unique=False)
    op.create_index(op.f('ix_user_subcategories_owner_id'), 'user_subcategories', ['owner_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_isolated', sa.Boolean(), nullable=False),
    sa.Column('origin_goal_id', sa.Integer(), nullable=True),
    sa.Column('total_limit', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('wallet_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['financial_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_event_id'), 'wallet_ledger', ['event_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_id'), 'wallet_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_owner_id'), 'wallet_ledger', ['owner_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_wallet_id'), 'wallet_ledger', ['wallet_id'], unique=False)
    op.create_table('entity_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'ELECTRONICS', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'PERSONAL_CARE', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'BANK_FEES_INTEREST', 'DEBT_CHARGES', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', name='expensecategory', create_type=False), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('income_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['financial_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['user_subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_ledger_event_id'), 'entity_ledger', ['event_id'], unique=False)
    op.create_index(op.f('ix_entity_ledger_id'), 'entity_ledger', ['id'], unique=False)
    op.create_table('project_category_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'ELECTRONICS', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'PERSONAL_CARE', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'BANK_FEES_INTEREST', 'DEBT_CHARGES', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', name='expensecategory', create_type=False), nullable=False),
    sa.Column('limit_amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'category', name='uq_project_category_limits')
    )
    op.create_index(op.f('ix_project_category_limits_id'), 'project_category_limits', ['id'], unique=False)
    op.create_index(op.f('ix_project_category_limits_project_id'), 'project_category_limits', ['project_id'], unique=False)
    op.drop_index(op.f('ix_transactions_budget_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_debt_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_income_source_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_owner_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_owner_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recurring_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_constraint(op.f('debts_linked_transaction_id_fkey'), 'debts', type_='foreignkey')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_expenses_budget_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_wallet_id'), table_name='expenses')
    op.drop_constraint(op.f('installment_payments_expense_id_fkey'), 'installment_payments', type_='foreignkey')
    op.drop_table('expenses')
    op.add_column('budgets', sa.Column('max_envelope_balance', sa.BigInteger(), nullable=True))
    op.add_column('budgets', sa.Column('max_rollover_amount', sa.BigInteger(), nullable=True))
    op.add_column('budgets', sa.Column('rollover_mode', sa.String(length=10), nullable=True))
    op.add_column('budgets', sa.Column('sweep_target_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'goals', ['sweep_target_goal_id'], ['id'], ondelete='SET NULL')
    op.add_column('debts', sa.Column('linked_event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debts', 'financial_events', ['linked_event_id'], ['id'], ondelete='SET NULL')
    op.drop_column('debts', 'linked_transaction_id')
    op.add_column('installment_payments', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_installment_payments_expense_id'), table_name='installment_payments')
    op.create_index(op.f('ix_installment_payments_event_id'), 'installment_payments', ['event_id'], unique=False)
    op.create_foreign_key(None, 'installment_payments', 'financial_events', ['event_id'], ['id'], ondelete='SET NULL')
    op.drop_column('installment_payments', 'expense_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payments', sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'installment_payments', type_='foreignkey')
    op.create_foreign_key(op.f('installment_payments_expense_id_fkey'), 'installment_payments', 'expenses', ['expense_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_installment_payments_event_id'), table_name='installment_payments')
    op.create_index(op.f('ix_installment_payments_expense_id'), 'installment_payments', ['expense_id'], unique=False)
    op.drop_column('installment_payments', 'event_id')
    op.add_column('debts', sa.Column('linked_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.create_foreign_key(op.f('debts_linked_transaction_id_fkey'), 'debts', 'transactions', ['linked_transaction_id'], ['id'], ondelete='SET NULL')
    op.drop_column('debts', 'linked_event_id')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'sweep_target_goal_id')
    op.drop_column('budgets', 'rollover_mode')
    op.drop_column('budgets', 'max_rollover_amount')
    op.drop_column('budgets', 'max_envelope_balance')
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'ELECTRONICS', 'PERSONAL_CARE', 'BANK_FEES_INTEREST', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', 'DEBT_CHARGES', name='expensecategory'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("date >= '2020-01-01'::date", name=op.f('ck_expenses_date_min_2020_01_01')),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_expenses_budget_id_budgets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('expenses_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('expenses_wallet_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('ix_expenses_wallet_id'), 'expenses', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_budget_id'), 'expenses', ['budget_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('EXPENSE', 'INCOME', 'TRANSFER', 'REFUND', 'ADJUSTMENT', 'DEBT_SETTLEMENT', 'NEUTRAL_FLOW', name='transactiontype'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'ELECTRONICS', 'PERSONAL_CARE', 'BANK_FEES_INTEREST', 'TRAVEL', 'CHARITY', 'ANIMALS_PETS', 'DEBT_CHARGES', name='expensecategory'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('related_wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('recurring_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('debt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('income_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('transactions_budget_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name=op.f('transactions_debt_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_sources.id'], name=op.f('fk_transactions_income_source_id_income_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], name=op.f('transactions_original_transaction_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('transactions_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_expenses.id'], name=op.f('transactions_recurring_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_wallet_id'], ['wallets.id'], name=op.f('transactions_related_wallet_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('transactions_wallet_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('transactions_idempotency_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_recurring_id'), 'transactions', ['recurring_id'], unique=False)
    op.create_index(op.f('ix_transactions_owner_id'), 'transactions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_transactions_owner_date'), 'transactions', ['owner_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_income_source_id'), 'transactions', ['income_source_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_debt_id'), 'transactions', ['debt_id'], unique=False)
    op.create_index(op.f('ix_transactions_budget_id'), 'transactions', ['budget_id'], unique=False)
    op.drop_index(op.f('ix_project_category_limits_project_id'), table_name='project_category_limits')
    op.drop_index(op.f('ix_project_category_limits_id'), table_name='project_category_limits')
    op.drop_table('project_category_limits')
    op.drop_index(op.f('ix_entity_ledger_id'), table_name='entity_ledger')
    op.drop_index(op.f('ix_entity_ledger_event_id'), table_name='entity_ledger')
    op.drop_table('entity_ledger')
    op.drop_index(op.f('ix_wallet_ledger_wallet_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_owner_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_event_id'), table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_user_subcategories_owner_id'), table_name='user_subcategories')
    op.drop_index('ix_user_subcategories_owner_category', table_name='user_subcategories')
    op.drop_index(op.f('ix_user_subcategories_id'), table_name='user_subcategories')
    op.drop_table('user_subcategories')
    op.drop_index(op.f('ix_financial_events_owner_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_type'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index('ix_budget_ledger_lookup', table_name='budget_ledger')
    op.drop_index(op.f('ix_budget_ledger_id'), table_name='budget_ledger')
    op.drop_table('budget_ledger')
    # ### end Alembic commands ###
