"""Add Transaction ledger

Revision ID: 12f2080d6dd6
Revises: 4a4137a6643b
Create Date: 2026-04-17 01:08:11.555876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '12f2080d6dd6'
down_revision: Union[str, Sequence[str], None] = '4a4137a6643b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', 'FEE', 'INTEREST', 'REFUND', 'ADJUSTMENT', 'DEBT_PAYMENT', 'INSTALLMENT_PAYMENT', 'SAVINGS_DEPOSIT', 'SAVINGS_WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('category', postgresql.ENUM('GROCERIES', 'DINING_OUT', 'ELECTRONICS', 'HOUSING', 'UTILITIES', 'SUBSCRIPTIONS', 'TRANSPORT', 'HEALTH', 'PERSONAL_CARE', 'EDUCATION', 'CLOTHING', 'FAMILY_EVENTS', 'ENTERTAINMENT', 'INSTALLMENTS_DEBT', 'BUSINESS_WORK', 'BANK_FEES_INTEREST', name='expensecategory', create_type=False), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('related_wallet_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('original_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_budget_id'), 'transactions', ['budget_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_owner_date', 'transactions', ['owner_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_owner_id'), 'transactions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.add_column('wallets', sa.Column('billing_cycle_start_day', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('payment_due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'payment_due_day')
    op.drop_column('wallets', 'billing_cycle_start_day')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_owner_id'), table_name='transactions')
    op.drop_index('ix_transactions_owner_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_budget_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
