"""add_wallets_and_multi_status

Revision ID: 15f7fd24a45c
Revises: 962919bbcfba
Create Date: 2026-04-11 18:21:35.580264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15f7fd24a45c'
down_revision: Union[str, Sequence[str], None] = '962919bbcfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('initial_balance', sa.BigInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('initial_balance >= 0', name='ck_wallets_initial_balance_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index('ix_wallets_owner_id', 'wallets', ['owner_id'], unique=False)
    op.create_table('wallet_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('from_wallet_id', sa.Integer(), nullable=False),
    sa.Column('to_wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_wallet_transfers_amount_positive'),
    sa.CheckConstraint('from_wallet_id != to_wallet_id', name='ck_wallet_transfers_different_wallets'),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transfers_id'), 'wallet_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_owner_id'), 'wallet_transfers', ['owner_id'], unique=False)
    op.add_column('user_profiles', sa.Column('life_statuses', sa.JSON(), server_default='[]', nullable=False))
    op.alter_column('user_profiles', 'life_status',
               existing_type=postgresql.ENUM('STUDENT', 'EMPLOYED', 'SELF_EMPLOYED', 'BUSINESS_OWNER', 'UNEMPLOYED', name='lifestatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'life_status',
               existing_type=postgresql.ENUM('STUDENT', 'EMPLOYED', 'SELF_EMPLOYED', 'BUSINESS_OWNER', 'UNEMPLOYED', name='lifestatus'),
               nullable=False)
    op.drop_column('user_profiles', 'life_statuses')
    op.drop_index(op.f('ix_wallet_transfers_owner_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_id'), table_name='wallet_transfers')
    op.drop_table('wallet_transfers')
    op.drop_index('ix_wallets_owner_id', table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
