"""session_assets_v1

Revision ID: 18c1e7e399cd
Revises: 12e4dc0b67b8
Create Date: 2026-05-14 12:50:22.230608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c1e7e399cd'
down_revision: Union[str, Sequence[str], None] = '12e4dc0b67b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('origin_event_id', sa.Integer(), nullable=True),
    sa.Column('purchase_value', sa.BigInteger(), nullable=False),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sale_event_id', sa.Integer(), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sale_value', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_value >= 0', name='ck_assets_current_value_non_negative'),
    sa.CheckConstraint('purchase_value > 0', name='ck_assets_purchase_value_positive'),
    sa.ForeignKeyConstraint(['origin_event_id'], ['financial_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_event_id'], ['financial_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index('ix_assets_owner_status', 'assets', ['owner_id', 'status'], unique=False)
    op.add_column('entity_ledger', sa.Column('label', sa.String(length=100), nullable=True))
    op.add_column('entity_ledger', sa.Column('original_amount', sa.BigInteger(), nullable=True))
    op.add_column('financial_events', sa.Column('is_session', sa.Boolean(), nullable=False))
    op.add_column('financial_events', sa.Column('discount_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_events', 'discount_amount')
    op.drop_column('financial_events', 'is_session')
    op.drop_column('entity_ledger', 'original_amount')
    op.drop_column('entity_ledger', 'label')
    op.drop_index('ix_assets_owner_status', table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
