"""add_wallet_card_states_enum

Revision ID: 1dddd378d1d5
Revises: cc2663895d9d
Create Date: 2026-04-21 05:37:59.058515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dddd378d1d5'
down_revision: Union[str, Sequence[str], None] = 'cc2663895d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the Enum type in Postgres first
    wallet_status = sa.Enum('ACTIVE', 'FROZEN', 'BLOCKED', 'EXPIRED', 'ARCHIVED', name='walletstatus')
    wallet_status.create(op.get_bind())

    # 2. Add the column as nullable initially
    op.add_column('wallets', sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'BLOCKED', 'EXPIRED', 'ARCHIVED', name='walletstatus'), nullable=True))
    op.create_index(op.f('ix_wallets_status'), 'wallets', ['status'], unique=False)

    # 3. Backfill data based on the old 'is_active' boolean
    op.execute("UPDATE wallets SET status = 'ACTIVE' WHERE is_active = TRUE")
    op.execute("UPDATE wallets SET status = 'ARCHIVED' WHERE is_active = FALSE")

    # 4. Now make it non-nullable
    op.alter_column('wallets', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_status'), table_name='wallets')
    op.drop_column('wallets', 'status')
    # ### end Alembic commands ###
