"""add_forgiven_status_and_debt_charges

Revision ID: 27e091443c89
Revises: bb816212465d
Create Date: 2026-05-01 01:07:30.345316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e091443c89'
down_revision: Union[str, Sequence[str], None] = 'bb816212465d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add FORGIVEN to the debtstatus enum (Alembic can't auto-detect enum changes)
    op.execute("ALTER TYPE debtstatus ADD VALUE IF NOT EXISTS 'FORGIVEN' AFTER 'PAID'")

    # 2. Create debt_charges table
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <= 999999999999', name='ck_debt_charges_amount_limit'),
    sa.CheckConstraint('amount > 0', name='ck_debt_charges_amount_positive'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debt_charges_debt_id', 'debt_charges', ['debt_id'], unique=False)
    op.create_index(op.f('ix_debt_charges_id'), 'debt_charges', ['id'], unique=False)
    op.create_index(op.f('ix_debt_charges_owner_id'), 'debt_charges', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_charges_owner_id'), table_name='debt_charges')
    op.drop_index(op.f('ix_debt_charges_id'), table_name='debt_charges')
    op.drop_index('ix_debt_charges_debt_id', table_name='debt_charges')
    op.drop_table('debt_charges')
    # ### end Alembic commands ###
