"""remove_auto_record_and_retries

Revision ID: 351ec9a8d540
Revises: a0b1c2d3e4f6
Create Date: 2026-06-22 14:13:36.411465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '351ec9a8d540'
down_revision: Union[str, Sequence[str], None] = 'a0b1c2d3e4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_expenses', 'retry_count')
    op.drop_column('recurring_expenses', 'failing_due_date')
    op.drop_column('recurring_expenses', 'recording_mode')
    op.drop_column('recurring_expenses', 'last_retry_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_expenses', sa.Column('last_retry_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('recurring_expenses', sa.Column('recording_mode', postgresql.ENUM('CONFIRM_EACH', 'AUTO_RECORD', name='recurringrecordingmode'), server_default=sa.text("'AUTO_RECORD'::recurringrecordingmode"), autoincrement=False, nullable=False))
    op.add_column('recurring_expenses', sa.Column('failing_due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('recurring_expenses', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
