"""add_wallet_balance_cache

Revision ID: 442c5a94ed01
Revises: a4051aea7ac6
Create Date: 2026-04-13 19:52:53.912733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442c5a94ed01'
down_revision: Union[str, Sequence[str], None] = 'a4051aea7ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first to allow existing rows
    op.add_column('wallets', sa.Column('current_balance', sa.BigInteger(), nullable=True))
    
    # 2. Add the check constraint
    op.create_check_constraint(
        'ck_wallets_current_balance_non_negative',
        'wallets',
        'current_balance >= 0'
    )

    # 3. Data Seeding: Calculate current balance for all existing wallets
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # We need to reflect the tables to use them in queries
    meta = sa.MetaData()
    wallets_t = sa.Table('wallets', meta, autoload_with=bind)
    expenses_t = sa.Table('expenses', meta, autoload_with=bind)
    income_t = sa.Table('income_entries', meta, autoload_with=bind)
    transfers_t = sa.Table('wallet_transfers', meta, autoload_with=bind)
    savings_t = sa.Table('savings_transactions', meta, autoload_with=bind)
    debts_t = sa.Table('debts', meta, autoload_with=bind)
    debt_tx_t = sa.Table('debt_transactions', meta, autoload_with=bind)

    wallets = session.execute(sa.select(wallets_t)).all()

    for wallet in wallets:
        w_id = wallet.id
        
        # Subqueries for sums
        expenses = session.execute(sa.select(sa.func.coalesce(sa.func.sum(expenses_t.c.amount), 0)).where(expenses_t.c.wallet_id == w_id)).scalar() or 0
        incomes = session.execute(sa.select(sa.func.coalesce(sa.func.sum(income_t.c.amount), 0)).where(income_t.c.wallet_id == w_id)).scalar() or 0
        
        t_out = session.execute(sa.select(sa.func.coalesce(sa.func.sum(transfers_t.c.amount), 0)).where(transfers_t.c.from_wallet_id == w_id)).scalar() or 0
        t_in = session.execute(sa.select(sa.func.coalesce(sa.func.sum(transfers_t.c.amount), 0)).where(transfers_t.c.to_wallet_id == w_id)).scalar() or 0
        
        s_dep = session.execute(sa.select(sa.func.coalesce(sa.func.sum(savings_t.c.amount), 0)).where(sa.and_(savings_t.c.wallet_id == w_id, savings_t.c.transaction_type == 'DEPOSIT'))).scalar() or 0
        s_wd = session.execute(sa.select(sa.func.coalesce(sa.func.sum(savings_t.c.amount), 0)).where(sa.and_(savings_t.c.wallet_id == w_id, savings_t.c.transaction_type == 'WITHDRAWAL'))).scalar() or 0
        
        # Debts: Initial amounts
        d_in = session.execute(sa.select(sa.func.coalesce(sa.func.sum(debts_t.c.initial_amount), 0)).where(sa.and_(debts_t.c.initial_wallet_id == w_id, debts_t.c.is_money_transferred == True, debts_t.c.debt_type == 'OWING'))).scalar() or 0
        d_out = session.execute(sa.select(sa.func.coalesce(sa.func.sum(debts_t.c.initial_amount), 0)).where(sa.and_(debts_t.c.initial_wallet_id == w_id, debts_t.c.is_money_transferred == True, debts_t.c.debt_type == 'OWED'))).scalar() or 0

        # Debts: Payments
        # We need to join with debts to get the type
        join_stmt_in = sa.select(sa.func.coalesce(sa.func.sum(debt_tx_t.c.amount), 0)).select_from(debt_tx_t.join(debts_t, debt_tx_t.c.debt_id == debts_t.c.id)).where(sa.and_(debt_tx_t.c.wallet_id == w_id, debts_t.c.debt_type == 'OWED'))
        dtx_in = session.execute(join_stmt_in).scalar() or 0

        join_stmt_out = sa.select(sa.func.coalesce(sa.func.sum(debt_tx_t.c.amount), 0)).select_from(debt_tx_t.join(debts_t, debt_tx_t.c.debt_id == debts_t.c.id)).where(sa.and_(debt_tx_t.c.wallet_id == w_id, debts_t.c.debt_type == 'OWING'))
        dtx_out = session.execute(join_stmt_out).scalar() or 0

        # Final Calc
        balance = (
            wallet.initial_balance 
            - expenses 
            + incomes 
            - t_out 
            + t_in 
            - s_dep 
            + s_wd 
            + d_in 
            - d_out 
            + dtx_in 
            - dtx_out
        )
        
        # Update wallet
        # If balance is negative (invalid in new system), we force it to 0 for migration safety
        if balance < 0:
            balance = 0
            
        session.execute(sa.update(wallets_t).where(wallets_t.c.id == w_id).values(current_balance=balance))

    session.commit()

    # 4. Make column NOT NULL
    op.alter_column('wallets', 'current_balance', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'current_balance')
    # ### end Alembic commands ###
