"""fix: sync index rename and enum typo

Revision ID: 51ff4b081d2d
Revises: a1b2c3d4e5f7
Create Date: 2026-07-27 14:00:46.332149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ff4b081d2d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iso_proj_subcat_alloc_category_alloc_id'), table_name='isolated_project_subcategory_allocations')
    op.create_index(op.f('ix_isolated_project_subcategory_allocations_category_allocation_id'), 'isolated_project_subcategory_allocations', ['category_allocation_id'], unique=False)
    op.alter_column('payment_plans', 'schedule_model',
               existing_type=postgresql.ENUM('FLAT_TOTAL', 'AMORTIZED_LOAN', 'MANUAL_CONTRACT_SCHEDULE', name='schemodel'),
               type_=sa.Enum('FLAT_TOTAL', 'AMORTIZED_LOAN', 'MANUAL_CONTRACT_SCHEDULE', name='schedulemodel'),
               existing_nullable=False,
               existing_server_default=sa.text("'FLAT_TOTAL'::schemodel"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_plans', 'schedule_model',
               existing_type=sa.Enum('FLAT_TOTAL', 'AMORTIZED_LOAN', 'MANUAL_CONTRACT_SCHEDULE', name='schedulemodel'),
               type_=postgresql.ENUM('FLAT_TOTAL', 'AMORTIZED_LOAN', 'MANUAL_CONTRACT_SCHEDULE', name='schemodel'),
               existing_nullable=False,
               existing_server_default=sa.text("'FLAT_TOTAL'::schemodel"))
    op.drop_index(op.f('ix_isolated_project_subcategory_allocations_category_allocation_id'), table_name='isolated_project_subcategory_allocations')
    op.create_index(op.f('ix_iso_proj_subcat_alloc_category_alloc_id'), 'isolated_project_subcategory_allocations', ['category_allocation_id'], unique=False)
    # ### end Alembic commands ###
