"""add savings and goals tables

Revision ID: 57f9d7b1ef60
Revises: f2a7d88f4c31
Create Date: 2026-03-13 02:56:32.181262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f9d7b1ef60'
down_revision: Union[str, Sequence[str], None] = 'f2a7d88f4c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('target_amount', sa.BigInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_amount > 0', name='ck_goals_target_amount_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_owner_id'), 'goals', ['owner_id'], unique=False)
    op.create_index('ix_goals_owner_status', 'goals', ['owner_id', 'status'], unique=False)
    op.create_table('savings_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='savingstransactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_savings_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_savings_transactions_owner_created_at', 'savings_transactions', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_savings_transactions_owner_id'), 'savings_transactions', ['owner_id'], unique=False)
    op.create_table('goal_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('contribution_type', sa.Enum('ALLOCATE', 'RETURN', name='goalcontributiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_goal_contributions_amount_positive'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_contributions_goal_created_at', 'goal_contributions', ['goal_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_goal_contributions_goal_id'), 'goal_contributions', ['goal_id'], unique=False)
    op.create_index('ix_goal_contributions_owner_created_at', 'goal_contributions', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_goal_contributions_owner_id'), 'goal_contributions', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_contributions_owner_id'), table_name='goal_contributions')
    op.drop_index('ix_goal_contributions_owner_created_at', table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_goal_id'), table_name='goal_contributions')
    op.drop_index('ix_goal_contributions_goal_created_at', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index(op.f('ix_savings_transactions_owner_id'), table_name='savings_transactions')
    op.drop_index('ix_savings_transactions_owner_created_at', table_name='savings_transactions')
    op.drop_table('savings_transactions')
    op.drop_index('ix_goals_owner_status', table_name='goals')
    op.drop_index(op.f('ix_goals_owner_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
