"""add_title_to_transaction

Revision ID: 600477736318
Revises: d8c0b7a1e4f2
Create Date: 2026-04-24 06:35:30.105774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600477736318'
down_revision: Union[str, Sequence[str], None] = 'd8c0b7a1e4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('title', sa.String(length=32), nullable=True))
    
    # Data Migration: Split 'title - description' back into separate columns
    op.execute("""
        UPDATE transactions 
        SET 
          title = CASE 
            WHEN description LIKE '%% - %%' THEN split_part(description, ' - ', 1)
            ELSE substring(description from 1 for 32)
          END,
          description = CASE 
            WHEN description LIKE '%% - %%' THEN split_part(description, ' - ', 2)
            ELSE NULL
          END
        WHERE title IS NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'title')
    # ### end Alembic commands ###
