"""add linked_transaction_id to debts

Revision ID: 7793d5500b70
Revises: 600477736318
Create Date: 2026-04-24 12:04:37.847065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7793d5500b70'
down_revision: Union[str, Sequence[str], None] = '600477736318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debts', 'transactions', ['linked_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_column('debts', 'linked_transaction_id')
    # ### end Alembic commands ###
