"""v3_recurring_architecture

Revision ID: 7dddb8a1026e
Revises: 16d12b4139cf
Create Date: 2026-04-28 18:21:04.897929

"""
from typing import Sequence, Union

from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dddb8a1026e'
down_revision: Union[str, Sequence[str], None] = '16d12b4139cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'PAID', 'SKIPPED', 'FAILED', 'UPDATED', 'RESUMED', name='recurringeventtype'), nullable=False),
    sa.Column('target_due_date', sa.Date(), nullable=False),
    sa.Column('old_next_due_date', sa.Date(), nullable=True),
    sa.Column('new_next_due_date', sa.Date(), nullable=True),
    sa.Column('metadata_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_events_id'), 'recurring_events', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_events_recurring_expense_id'), 'recurring_events', ['recurring_expense_id'], unique=False)
    op.add_column('recurring_expenses', sa.Column('failing_due_date', sa.Date(), nullable=True))

    op.add_column('transactions', sa.Column('recurring_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_transactions_recurring_id'), 'transactions', ['recurring_id'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['idempotency_key'])
    op.create_foreign_key(None, 'transactions', 'recurring_expenses', ['recurring_id'], ['id'], ondelete='SET NULL')
    
    # --- DATA RESCUE BLOCK ---
    # 1. Capture failing state into the new failing_due_date column
    op.execute("UPDATE recurring_expenses SET failing_due_date = next_due_date WHERE status IN ('RETRYING', 'PAUSED')")
    
    # 2. Reset status to ACTIVE for all legacy templates (now that failures are in failing_due_date)
    op.execute("UPDATE recurring_expenses SET status = 'ACTIVE' WHERE status IN ('RETRYING', 'PAUSED')")
    
    # 3. Backfill original_due_day from start_date for Monthly Fixed expenses
    # Using EXTRACT to grab the day of the month from the start_dateFact.
    op.execute("UPDATE recurring_expenses SET original_due_day = EXTRACT(DAY FROM start_date) WHERE frequency = 'MONTHLY' AND cycle_behavior = 'FIXED' AND original_due_day IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_recurring_id'), table_name='transactions')
    op.drop_column('transactions', 'idempotency_key')
    op.drop_column('transactions', 'recurring_id')

    op.drop_column('recurring_expenses', 'failing_due_date')
    op.drop_index(op.f('ix_recurring_events_recurring_expense_id'), table_name='recurring_events')
    op.drop_index(op.f('ix_recurring_events_id'), table_name='recurring_events')
    op.drop_table('recurring_events')
    # ### end Alembic commands ###
