"""split_debts_nasiya

Revision ID: 962919bbcfba
Revises: add_debts_tables
Create Date: 2026-04-08 20:23:36.625939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '962919bbcfba'
down_revision: Union[str, Sequence[str], None] = 'add_debts_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE debts CASCADE")
    op.execute("DROP TYPE IF EXISTS installmentfrequency CASCADE")
    op.execute("DROP TYPE IF EXISTS installmentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS installmentpaymentstatus CASCADE")
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('store_or_bank_name', sa.String(length=100), nullable=True),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('down_payment', sa.BigInteger(), nullable=False),
    sa.Column('remaining_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='installmentfrequency'), nullable=False),
    sa.Column('monthly_payment_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAID', 'ARCHIVED', name='installmentstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('down_payment >= 0', name='ck_installments_down_payment_non_negative'),
    sa.CheckConstraint('months > 0', name='ck_installments_months_positive'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_installments_remaining_amount_non_negative'),
    sa.CheckConstraint('total_price > 0', name='ck_installments_total_price_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_plans_id'), 'installment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_installment_plans_owner_id'), 'installment_plans', ['owner_id'], unique=False)
    op.create_index('ix_installments_owner_status', 'installment_plans', ['owner_id', 'status'], unique=False)
    op.create_table('debt_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_debt_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_transactions_debt_id'), 'debt_transactions', ['debt_id'], unique=False)
    op.create_index(op.f('ix_debt_transactions_id'), 'debt_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_debt_transactions_owner_id'), 'debt_transactions', ['owner_id'], unique=False)
    op.create_table('installment_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SKIPPED', name='installmentpaymentstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_installment_payments_amount_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_payments_expense_id'), 'installment_payments', ['expense_id'], unique=False)
    op.create_index(op.f('ix_installment_payments_id'), 'installment_payments', ['id'], unique=False)
    op.create_index('ix_installment_payments_owner_due_date', 'installment_payments', ['owner_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_installment_payments_owner_id'), 'installment_payments', ['owner_id'], unique=False)
    op.create_index('ix_installment_payments_plan_due_date', 'installment_payments', ['plan_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_installment_payments_plan_id'), 'installment_payments', ['plan_id'], unique=False)
    op.drop_index(op.f('ix_debt_payments_debt_due_date'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_debt_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_owner_due_date'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_owner_id'), table_name='debt_payments')
    op.drop_table('debt_payments')
    op.add_column('debts', sa.Column('counterparty_name', sa.String(length=100), nullable=False))
    op.add_column('debts', sa.Column('initial_amount', sa.BigInteger(), nullable=False))
    op.add_column('debts', sa.Column('remaining_amount', sa.BigInteger(), nullable=False))
    op.add_column('debts', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('debts', sa.Column('expected_return_date', sa.Date(), nullable=True))
    op.alter_column('debts', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.drop_column('debts', 'interest_percent')
    op.drop_column('debts', 'cash_price')
    op.drop_column('debts', 'start_date')
    op.drop_column('debts', 'title')
    op.drop_column('debts', 'down_payment')
    op.drop_column('debts', 'total_amount')
    op.drop_column('debts', 'is_installment_plan')
    op.drop_column('debts', 'paid_amount')
    op.drop_column('debts', 'installment_count')
    op.drop_column('debts', 'due_date')
    op.drop_column('debts', 'creditor_name')
    op.drop_column('debts', 'affects_balance')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.add_column('debts', sa.Column('affects_balance', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('creditor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('installment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('paid_amount', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('is_installment_plan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('total_amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('down_payment', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('installment_frequency', postgresql.ENUM('WEEKLY', 'MONTHLY', 'CUSTOM', name='installmentfrequency'), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('debts', sa.Column('cash_price', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('interest_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.alter_column('debts', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('debts', 'expected_return_date')
    op.drop_column('debts', 'date')
    op.drop_column('debts', 'remaining_amount')
    op.drop_column('debts', 'initial_amount')
    op.drop_column('debts', 'counterparty_name')
    op.create_table('debt_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('debt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_type', postgresql.ENUM('SCHEDULED', 'MANUAL', name='debtpaymenttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'SKIPPED', name='debtpaymentstatus'), server_default=sa.text("'PENDING'::debtpaymentstatus"), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('paid_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_debt_payments_amount_positive')),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name=op.f('debt_payments_debt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('debt_payments_expense_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('debt_payments_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('debt_payments_pkey'))
    )
    op.create_index(op.f('ix_debt_payments_owner_id'), 'debt_payments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_owner_due_date'), 'debt_payments', ['owner_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_debt_payments_debt_id'), 'debt_payments', ['debt_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_debt_due_date'), 'debt_payments', ['debt_id', 'due_date'], unique=False)
    op.drop_index(op.f('ix_installment_payments_plan_id'), table_name='installment_payments')
    op.drop_index('ix_installment_payments_plan_due_date', table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_owner_id'), table_name='installment_payments')
    op.drop_index('ix_installment_payments_owner_due_date', table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_id'), table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_expense_id'), table_name='installment_payments')
    op.drop_table('installment_payments')
    op.drop_index(op.f('ix_debt_transactions_owner_id'), table_name='debt_transactions')
    op.drop_index(op.f('ix_debt_transactions_id'), table_name='debt_transactions')
    op.drop_index(op.f('ix_debt_transactions_debt_id'), table_name='debt_transactions')
    op.drop_table('debt_transactions')
    op.drop_index('ix_installments_owner_status', table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_owner_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_id'), table_name='installment_plans')
    op.drop_table('installment_plans')
    # ### end Alembic commands ###
