"""Add money transfer fields to Debt

Revision ID: a4051aea7ac6
Revises: fb5cf616da8a
Create Date: 2026-04-12 21:07:06.748486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4051aea7ac6'
down_revision: Union[str, Sequence[str], None] = 'fb5cf616da8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first to handle existing data
    op.add_column('debts', sa.Column('is_money_transferred', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE debts SET is_money_transferred = FALSE")
    
    # Now set to non-nullable
    op.alter_column('debts', 'is_money_transferred', nullable=False)
    
    op.add_column('debts', sa.Column('initial_wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debts', 'wallets', ['initial_wallet_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_column('debts', 'initial_wallet_id')
    op.drop_column('debts', 'is_money_transferred')
    # ### end Alembic commands ###
