"""refine_wallet_initial_balance_constraint

Revision ID: b2e8d12c3eb3
Revises: 9a9df9b0aece
Create Date: 2026-04-19 10:18:01.654670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e8d12c3eb3'
down_revision: Union[str, Sequence[str], None] = '9a9df9b0aece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_wallets_initial_balance_non_negative', 'wallets', type_='check')
    op.create_check_constraint(
        'ck_wallets_initial_balance_integrity',
        'wallets',
        "(wallet_type = 'CREDIT') OR "
        "(wallet_type = 'CASH' AND initial_balance >= 0) OR "
        "((wallet_type = 'DEBIT' OR wallet_type = 'PRELOADED') AND (has_overdraft = TRUE OR initial_balance >= 0))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_wallets_initial_balance_integrity', 'wallets', type_='check')
    op.create_check_constraint(
        'ck_wallets_initial_balance_non_negative',
        'wallets',
        'initial_balance >= 0'
    )
    # ### end Alembic commands ###
