"""add_pro_frequencies

Revision ID: bb816212465d
Revises: 7dddb8a1026e
Create Date: 2026-04-29 10:37:39.824940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb816212465d'
down_revision: Union[str, Sequence[str], None] = '7dddb8a1026e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres doesn't allow adding ENUM values in a transaction block easily
    # but Alembic op.execute runs them. We use autocommit-style here.
    op.execute("ALTER TYPE recurringfrequency ADD VALUE 'ONE_TIME'")
    op.execute("ALTER TYPE recurringfrequency ADD VALUE 'BIWEEKLY'")
    op.execute("ALTER TYPE recurringfrequency ADD VALUE 'QUARTERLY'")
    op.execute("ALTER TYPE recurringfrequency ADD VALUE 'SEMI_ANNUALLY'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
