"""added_recurring_expenses_and_premium

Revision ID: c36276b796d0
Revises: 799f8b552bf7
Create Date: 2026-03-04 11:52:20.408710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36276b796d0'
down_revision: Union[str, Sequence[str], None] = '799f8b552bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    expense_category_enum = ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'ENTERTAINMENT', 'UTILITIES', 'OTHER', name='expensecategory', create_type=False)
    recurring_frequency_enum = ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringfrequency', create_type=True)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('category', expense_category_enum, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequency', recurring_frequency_enum, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("start_date >= '2020-01-01'", name='ck_recurring_expenses_start_date_min_2020_01_01'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_id'), 'recurring_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_next_due_date'), 'recurring_expenses', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_owner_id'), 'recurring_expenses', ['owner_id'], unique=False)
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'is_premium')
    op.drop_index(op.f('ix_recurring_expenses_owner_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_next_due_date'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
