"""add is_deleted to usersubcategory

Revision ID: e547db0098d8
Revises: 351ec9a8d540
Create Date: 2026-06-25 19:17:56.579483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e547db0098d8'
down_revision: Union[str, Sequence[str], None] = '351ec9a8d540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subcategories', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subcategories', 'is_deleted')
    # ### end Alembic commands ###
