"""add password reset tokens and tighten user flags

Revision ID: fb38ec4f2277
Revises: f832c149cae6
Create Date: 2026-02-21 04:54:19.321815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb38ec4f2277'
down_revision: Union[str, Sequence[str], None] = 'f832c149cae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token_hash', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('used_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token_hash')
                    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'),
                    'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'),
                    'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'),
                    'password_reset_tokens', ['user_id'], unique=False)
    op.execute("UPDATE users SET is_verified = FALSE WHERE is_verified IS NULL")
    op.alter_column('users', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'),
                  table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'),
                  table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'),
                  table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
