"""link_transactions_to_wallets

Revision ID: fb5cf616da8a
Revises: 15f7fd24a45c
Create Date: 2026-04-11 18:42:05.941768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5cf616da8a'
down_revision: Union[str, Sequence[str], None] = '15f7fd24a45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt_transactions', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_debt_transactions_wallet_id'), 'debt_transactions', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'debt_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='SET NULL')
    op.add_column('expenses', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_wallet_id'), 'expenses', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'wallets', ['wallet_id'], ['id'], ondelete='SET NULL')
    op.add_column('income_entries', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_income_entries_wallet_id'), 'income_entries', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'income_entries', 'wallets', ['wallet_id'], ['id'], ondelete='SET NULL')
    op.add_column('savings_transactions', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_savings_transactions_wallet_id'), 'savings_transactions', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'savings_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_savings_transactions_wallet_id'), table_name='savings_transactions')
    op.drop_column('savings_transactions', 'wallet_id')
    op.drop_constraint(None, 'income_entries', type_='foreignkey')
    op.drop_index(op.f('ix_income_entries_wallet_id'), table_name='income_entries')
    op.drop_column('income_entries', 'wallet_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_wallet_id'), table_name='expenses')
    op.drop_column('expenses', 'wallet_id')
    op.drop_constraint(None, 'debt_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_debt_transactions_wallet_id'), table_name='debt_transactions')
    op.drop_column('debt_transactions', 'wallet_id')
    # ### end Alembic commands ###
