"""limit expense title to 32 chars

Revision ID: fd62fab1afc5
Revises: fb38ec4f2277
Create Date: 2026-02-23 09:29:43.675924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd62fab1afc5'
down_revision: Union[str, Sequence[str], None] = 'fb38ec4f2277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
