export { setAccessToken, isLoggedIn, silentRefresh } from "./api/client";
export { apiClient } from "./api/client";

export {
    signin,
    signup,
    forgotPassword,
    resendVerification,
    verifyEmail,
    resetPassword,
    logout,
    getGoogleLoginUrl,
} from "./api/auth";

export { getHealth } from "./api/health";
export { getCurrentUser, togglePremium, upsertOnboardingProfile } from "./api/users";
export { getCategories } from "./api/meta";
export {
    getBudgets,
    getBudgetDetail,
    getBudgetMonthSummary,
    getBudgetSubcategories,
    reallocateBudget,
    createBudgetSubcategory,
    updateBudgetSubcategory,
    reallocateBudgetSubcategory,
    deleteBudgetSubcategory,
    createBudget,
    updateBudget,
    deleteBudget,
    configureBorrowingSurvival,
} from "./api/budgets";
export {
    getProjects,
    getProject,
    createProject,
    createOverlayProject,
    updateProject,
    stopProject,
    resumeProject,
    completeProject,
    reopenProject,
    getProjectDeletePreview,
    deleteProject,
    resolveProjectDeletion,
    createProjectCategoryLimit,
    updateProjectCategoryLimit,
    deleteProjectCategoryLimit,
    getProjectSubcategories,
    createProjectSubcategory,
    updateProjectSubcategory,
    deleteProjectSubcategory,
} from "./api/projects";
export {
    getExpenses,
    getExpenseDetail,
    deleteExpense,
    createExpense,
    updateExpense,
    exportExpensesCsv,
    refundExpense,
    splitExpense,
    markExpenseAsAsset,
    markExpenseAsRecurring,
    getExpenseMergeGroups,
    createExpenseMergeGroup,
    addExpensesToMergeGroup,
    removeExpenseFromMergeGroup,
} from "./api/expenses";
export {
    getActiveSessionDraft,
    createSessionDraft,
    updateSessionDraft,
    pauseSessionDraft,
    resumeSessionDraft,
    abandonSessionDraft,
    addSessionDraftItem,
    updateSessionDraftItem,
    deleteSessionDraftItem,
    addSessionWalletAllocation,
    updateSessionWalletAllocation,
    deleteSessionWalletAllocation,
    addSessionDraftSplit,
    updateSessionDraftSplit,
    deleteSessionDraftSplit,
    finalizeSessionDraft,
} from "./api/sessionDrafts";
export {
    getRecurringExpenses,
    createRecurringExpense,
    updateRecurringExpense,
    deleteRecurringExpense,
    patchRecurringActive,
    skipRecurringOccurrence,
    changeRecurringWallet,
    getRecurringEvents,
    getRecurringOccurrences
} from "./api/recurring";
export { getThisMonthStats, getDashboardSummary, getDailyTrend, getAnalyticsHistory, getMonthToDateTrend, getCategoryBreakdown } from "./api/analytics";
export {
    getIncomeSources,
    createIncomeSource,
    updateIncomeSource,
    updateIncomeSourceActive,
    deleteIncomeSource,
    getIncomeEntries,
    createIncomeEntry,
    updateIncomeEntry,
    deleteIncomeEntry,
    getMoneyIn,
} from "./api/income";
export { getSavingsSummary } from "./api/savings";
export {
    getGoals,
    getGoalFundingSummary,
    getGoalActivity,
    createGoal,
    updateGoal,
    contributeToGoal,
    returnFromGoal,
    consumeGoalAllocation,
    moveGoalFunding,
    useReserveGoal,
    recordGoalPurchase,
    recordGoalDebtPayment,
    graduateGoalToProject,
    releaseGoalToProject,
    archiveGoal,
    restoreGoal,
    deleteGoal,
} from "./api/goals";
export { getNotifications, getUnreadCount, markNotificationsRead, markAllNotificationsRead, deleteNotification } from "./api/notifications";
export {
    getDebtsSummary,
    getDebts,
    getDebt,
    getDebtDetails,
    getDebtActions,
    createDebt,
    updateDebt,
    archiveDebt,
    restoreDebt,
    deleteDebt,
    getDebtPayments,
    payWalletBackedObligation,
    recordDebtPayment,
    recordPayment,
    updatePayment,
    deleteTransaction,
    addDebtCharge,
    addCharge,
    forgiveDebt,
    forgiveDebtAmount,
    adjustDebtBalance,
    reverseDebtLedgerEntry,
    updateDebtFormalDetails,
    generatePaymentPlans,
} from "./api/debts";
export {
    getPaymentPlanSummary,
    getPaymentPlans,
    getPaymentPlan,
    getPaymentPlanDetails,
    createPaymentPlan,
    updatePaymentPlan,
    recordPaymentPlanPayment,
    markPaymentPlanPaymentPaid,
    writeOffPaymentPlanPayment,
    undoPaymentPlanPaymentWriteOff,
    undoLatestPaymentPlanPayment,
    addPaymentPlanCharge,
    deletePaymentPlan,
} from "./api/payment-plans";
export {
    getWallets,
    getWalletTransactions,
    createWallet,
    updateWallet,
    deleteWallet,
    transferFunds,
    setDefaultWallet,
    recordWalletFee,
    recordWalletInterest,
    reconcileWalletBalance,
} from "./api/wallets";
export { getAssets, getAsset, createAsset, updateAsset, sellAsset, giftAsset, disposeAsset, markAssetLost } from "./api/assets";
export {
    getExpectedInflows,
    getExpectedInflow,
    createExpectedInflow,
    updateExpectedInflow,
    deleteExpectedInflow,
    realizeExpectedInflow,
    rescheduleExpectedInflow,
    cancelExpectedInflow,
    writeOffExpectedInflow,
    reverseExpectedInflowWriteOff,
    reopenExpectedInflow,
    reconcileExpectedInflow,
    getExpectedInflowTimeline,
} from "./api/expectedInflows";
